import { TONE_TEXT_CLASS } from "./ui/Badge";
import { ExternalLink } from "./ui/ExternalLink";
import { IconStar } from "./ui/icons";
import { formatRating, pluralize } from "@/lib/format";
import { isUncertainGoogleMatch, ratingTone, type Tone } from "@/lib/presentation";
import type { GoogleReviewsBrief } from "@/lib/types";

const STAR_FILL_CLASS: Partial<Record<Tone, string>> = {
  positive: "text-emerald-500",
  warning: "text-amber-500",
  danger: "text-rose-500",
};

export function GoogleMark({ className = "" }: { className?: string }) {
  return (
    <span
      className={`inline-grid size-5 shrink-0 place-items-center rounded-md border border-line-strong bg-surface text-[11px] font-bold text-ink ${className}`}
    >
      <span aria-hidden="true">G</span>
      <span className="sr-only">Google</span>
    </span>
  );
}

export function StarRating({ rating, className = "" }: { rating: number; className?: string }) {
  const filledPercent = (Math.max(0, Math.min(5, rating)) / 5) * 100;
  const stars = Array.from({ length: 5 }, (_, index) => <IconStar key={index} className="shrink-0" />);
  return (
    <span aria-hidden="true" className={`relative inline-flex ${className}`}>
      <span className="flex text-line-strong">{stars}</span>
      <span className="absolute inset-y-0 left-0 overflow-hidden" style={{ width: `${filledPercent}%` }}>
        <span className={`flex ${STAR_FILL_CLASS[ratingTone(rating)]}`}>{stars}</span>
      </span>
    </span>
  );
}

interface GoogleRatingLineProps {
  google: GoogleReviewsBrief;
  size?: "compact" | "card" | "large";
  linked?: boolean;
  showMatchNote?: boolean;
  linkClassName?: string;
}

export function GoogleRatingLine({
  google,
  size = "card",
  linked = true,
  showMatchNote = true,
  linkClassName = "",
}: GoogleRatingLineProps) {
  const large = size === "large";

  if (google.status !== "ok") {
    return (
      <p className="flex items-start gap-2 text-sm text-ink-muted">
        <GoogleMark className="mt-px" />
        <span>{google.explanation}</span>
      </p>
    );
  }

  if (google.rating === null) {
    return (
      <p className="flex items-center gap-2 text-sm text-ink-muted">
        <GoogleMark />
        <span>{google.count === 0 ? "This Google Maps place has no reviews yet" : "Google rating unavailable"}</span>
      </p>
    );
  }

  const tone = ratingTone(google.rating);
  const countText = google.count === null ? "Google review count unavailable" : pluralize(google.count, "Google review");
  const content = (
    <span className="inline-flex flex-wrap items-center gap-x-2 gap-y-0.5">
      <GoogleMark />
      <span className="sr-only">rating</span>
      <StarRating rating={google.rating} className={large ? "text-2xl" : "text-base"} />
      <span className={`font-bold tabular-nums ${TONE_TEXT_CLASS[tone]} ${large ? "text-3xl" : "text-lg"}`}>
        {formatRating(google.rating)}
        <span className="sr-only"> out of 5</span>
      </span>
      {size === "compact" ? (
        <span className="basis-full text-sm text-ink-muted">{countText}</span>
      ) : (
        <span className={`text-ink-muted ${large ? "text-base" : "text-sm"}`}>· {countText}</span>
      )}
    </span>
  );

  return (
    <div className="space-y-0.5">
      {linked && google.maps_url ? (
        <ExternalLink href={google.maps_url} className={linkClassName}>
          {content}
        </ExternalLink>
      ) : (
        content
      )}
      {showMatchNote && isUncertainGoogleMatch(google) && (
        <p className="text-xs font-medium text-amber-800 dark:text-amber-300">Google match unverified — matched by address/location</p>
      )}
    </div>
  );
}

interface GoogleSummaryProps {
  google: GoogleReviewsBrief;
  clamp?: boolean;
  showReportLink?: boolean;
}

export function GoogleSummary({ google, clamp = false, showReportLink = false }: GoogleSummaryProps) {
  if (google.status !== "ok" || !google.summary) return null;
  return (
    <div>
      <p className={`leading-relaxed text-ink ${clamp ? "line-clamp-3 text-sm" : "text-base"}`}>“{google.summary}”</p>
      <p className="mt-1 flex flex-wrap items-center gap-x-2 text-[11px] text-ink-faint">
        <span>
          Google&apos;s review summary · {google.summary_disclosure ?? "AI-generated by Google"}
        </span>
        {showReportLink && google.summary_flag_url && (
          <ExternalLink href={google.summary_flag_url} className="text-[11px]">
            Report this summary
          </ExternalLink>
        )}
      </p>
    </div>
  );
}

interface GoogleCommentsSummaryProps {
  google: GoogleReviewsBrief;
  clamp?: boolean;
}

export function GoogleCommentsSummary({ google, clamp = false }: GoogleCommentsSummaryProps) {
  if (!google.comments_summary) return null;
  return (
    <div>
      <p className="text-[11px] font-semibold uppercase tracking-wider text-ink-faint">What Google reviewers say</p>
      <p className={`mt-0.5 leading-relaxed text-ink ${clamp ? `${google.summary ? "line-clamp-2" : "line-clamp-3"} text-sm` : "text-base"}`}>
        {google.comments_summary}
      </p>
      {google.comments_summary_method && (
        <p
          className={`mt-1 text-[11px] text-ink-faint ${clamp ? "line-clamp-1" : ""}`}
          title={clamp ? google.comments_summary_method : undefined}
        >
          {google.comments_summary_method}
        </p>
      )}
    </div>
  );
}
